export { default as Home } from './Home';
export { default as Series } from './Series';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as ProductDetail } from './ProductDetail';
export { default as Cart } from './Cart';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Orders } from './Orders';
